<?php

$title = 'Delete blog';
$this->headTitle($title);
?>
<style>
    .demo-card-wide.mdl-card {
        width: 512px;
        margin-top: 20px;;
    }
    .demo-card-wide > .mdl-card__title {
        color: #fff;
        height: 176px;
        background-color: #673ab7;
    }
    .demo-card-wide > .mdl-card__menu {
        color: #fff;
    }
</style>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
<div class="demo-card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text"><?php echo $this->escapeHtml($blog->title);?></h2>
    </div>
    <div class="mdl-card__supporting-text">
        <?php echo $this->escapeHtml($blog->body);?>
    </div>
</div>
</p>
<?php
$url = $this->url('blog', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $blog->id; ?>" />
        <input type="submit" name="del" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" value="Yes" />
        <input type="submit" name="del" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" value="No" />
    </div>
</form>