<?php
$title = 'My Blogs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="" href="<?php echo $this->url('blog', array('action'=>'add'));?>">Add new blog</a>
</p>

<table class="">
    <tr>
        <th class="">Title</th>
        <th class="">Body</th>
        <th class="">&nbsp;</th>
    </tr>
    <?php foreach ($this->blog as $blog) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($blog->title);?></td>
            <td><?php echo $this->escapeHtml($blog->body);?></td>
            <td>
                <a class="" href="<?php echo $this->url('blog',
                    array('action'=>'edit', 'id' => $blog->id));?>">Edit</a>
                <a class="" href="<?php echo $this->url('blog',
                    array('action'=>'delete', 'id' => $blog->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>