<?php
$title = 'My Blogs';
$this->headTitle($title);
?>
<style>
    .demo-card-wide.mdl-card {
        width: 512px;
        margin-top: 20px;;
    }
    .demo-card-wide > .mdl-card__title {
        color: #fff;
        height: 176px;
        background-color: #673ab7;
    }
    .demo-card-wide > .mdl-card__menu {
        color: #fff;
    }
</style>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="mdl-button mdl-js-button mdl-js-ripple-effect" href="<?php echo $this->url('blog', array('action'=>'add'));?>">Add new blog</a>
</p>


    <?php foreach ($this->paginator as $blog) : ?>
        <div class="demo-card-wide mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text"><?php echo $this->escapeHtml($blog->title);?></h2>
            </div>
            <div class="mdl-card__supporting-text">
                <?php echo $this->escapeHtml($blog->body);?>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="<?php echo $this->url('blog',
                    array('action'=>'edit', 'id' => $blog->id));?>">
                    Edit
                </a>
                <a class="mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect" href="<?php echo $this->url('blog',
                    array('action'=>'delete', 'id' => $blog->id));?>">
                    Delete
                </a>
            </div>
        </div>
    <?php endforeach; ?>

<?php

echo $this->paginationControl(
    $this->paginator,
    'sliding',
    'partial/partial/paginator.phtml',
    array(
        'route' => 'paginator'
    )
);
?>